#!/bin/bash

#builds the entire thesis

echo "building"

cd scripts
./buildlatex
cd ..

for f in introduction stateoftheart
do
    pandoc --biblatex "$f".md -o "$f".tex
done

#pdflatex promotion.tex
pdflatex --interaction nonstopmode -halt-on-error -file-line-error promotion.tex # >/dev/null

echo " <<<<<<<<<<<<<<<fertig>>>>>>>>>>>> "

#remove files only if everything is buid including toc and pdf annotations etc..
#rm *.aux *.log *.out *.xml *-blx.bib
#rm *.upa *.upb
#rm introduction.tex
