#!/bin/bash

#builds the entire thesis


TDIR=$PWD/..       #thesis directory
BDIR=$TDIR/build   #build directory
SDIR=$TDIR/scripts #scripts directory

echo "building in $BDIR."

#cd scripts
#./buildlatex
#cd ../..

#cp necessary latex files
cp $PWD/pygments.tex $BDIR
cp $PWD/main.tex $BDIR


#copy all latex files
for f in $TDIR/*.tex
do
    echo "copy $f"
    cp $f $BDIR
done

#convert all markdown files to latex
for f in $TDIR/*.md
do
    fs=${f%.*} #${f##*/}
    fn=${fs##*/} 
    echo "$fn"
    pandoc --biblatex "$TDIR/$fn.md" -o "$BDIR/$fn.tex"
done

#convert all jupyter files to latex
for f in $SDIR/*.ipynb
do
    #fs=${f%.*} #${f##*/}
    #fn=${fs##*/} 
    echo "$f"
    #echo "jupyter nbconvert --to latex --output-dir $BDIR --template chapter_nocode.tplx $SDIR/$fn.ipynb"
    jupyter nbconvert --to latex --output-dir $BDIR --template chapter_nocode.tplx "$f"
done

#copy latex build script into build directory
cp $PWD/pdfbuild $BDIR
cp acronyms/* $BDIR

#pdflatex promotion.tex
#pdflatex --interaction nonstopmode -halt-on-error -file-line-error promotion.tex # >/dev/null

echo " <<<<<<<<<<<<<<<fertig>>>>>>>>>>>> "

#remove files only if everything is buid including toc and pdf annotations etc..
#rm *.aux *.log *.out *.xml *-blx.bib
#rm *.upa *.upb
#rm introduction.tex
