#!/bin/bash

#builds the entire thesis

echo "building"

pandoc --biblatex introduction.md -o introduction.tex

#cd scripts
#sh buildlatex.sh
#cd ..

pdflatex promotion.tex
rm *.aux *.log *.out *.xml *-blx.bib
#rm *.upa *.upb
rm introduction.tex
