#!/bin/bash

#builds the entire thesis

echo "building"

for f in introduction stateoftheart
do
    pandoc --biblatex "$f".md -o "$f".tex
done
    
#cd scripts
#sh buildlatex.sh
#cd ..

#pdflatex promotion.tex
pdflatex --interaction nonstopmode -halt-on-error -file-line-error promotion.tex # >/dev/null

#remove files only if everything is buid including toc and pdf annotations etc..
#rm *.aux *.log *.out *.xml *-blx.bib
#rm *.upa *.upb
#rm introduction.tex
