#!/bin/bash

#converts all ipython notebooks to latex

for f in ../*.ipynb
do
    jupyter nbconvert --to latex --template chapter_nocode.tplx "$f"
done

echo " <<<<<<<<<<<<< fertig >>>>>>>>>>>>>>>>>>>>>>>>>>"

#pdflatex notebooks.tex

rm *.log *.aux
