#!/bin/bash

#builds the entire thesis

echo "building pdf with anotations and bibtex"

#OLDIR=$PWD
#DIR=$PWD/../build
DIR=$PWD
FN=$DIR/promotion

#cd $DIR

mkdir pictures
#pdflatex promotion.tex
#--shel-escape is there to enable \write18  which enables
#latex to execute shell commands. this way 
# imags from the web can be downloaded
#pdflatex --shell-escape --interaction nonstopmode $FN # >/dev/null
pdflatex --shell-escape --interaction batchmode -file-line-error $FN # >/dev/null
bibtex "$FN.aux"
#./acrofind
pdflatex --interaction batchmode -file-line-error $FN # >/dev/null
pdflatex --interaction batchmode -halt-on-error -file-line-error $FN # >/dev/null

#cd $OLDIR

echo " <<<<<<<<<<<<<<<pdf ready!!>>>>>>>>>>>> "

#remove files only if everything is buid including toc and pdf annotations etc..
#rm *.aux *.log *.out *.xml *-blx.bib
#rm *.upa *.upb
#rm introduction.tex
